version: "3.8"
services:
  backend1:
    image: uberman385/backend1:latest
    container_name: backend1
    build:
      context: ./Backend_1
      dockerfile: Dockerfile
    ports:
      - 3005:3005
    environment:
      - NODE_ENV=production
    volumes:
      - ./Backend_1:/app

  backend2:
    image: uberman385/backend2:latest
    container_name: backend2
    build:
      context: ./Backend_2
      dockerfile: Dockerfile
    ports:
      - 3006:3006
    environment:
      - NODE_ENV=production
    volumes:
      - ./Backend_2/:/app
