version: "3.8"
services:
  backend1:
    image: bun-backend1
    container_name: backend1
    build: ./Backend_1
    ports:
      - ${PORT1}:3006
    environment:
      - NODE_ENV=development
    depends_on:
      db1:
        condition: service_healthy
    networks:
      - mynetwork

  db1:
    image: postgres
    container_name: db1
    ports:
      - ${DB_PORT1}:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME1}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME1}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork
volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge
