name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted # config in server

    steps:
      - name: Pull Docker image for backend1
        run: sudo docker pull uberman385/backend1:latest

      - name: Pull Docker image for backend2
        run: sudo docker pull uberman385/backend2:latest

      - name: Stop and remove old containers
        run: |
          sudo docker rm -f backend1-container || true
          sudo docker rm -f backend2-container || true

      - name: Run Docker containers
        run: |
          sudo docker run -d -p 3005:3005 --name backend1-container uberman385/backend1:latest
          sudo docker run -d -p 3006:3006 --name backend2-container uberman385/backend2:latest
